### ISSUE TITLE
MacOS packages missing

### ISSUE THREAD

**Issue by ITDancer13** [cefsharp/cef-binary#107]
At the moment there are no NuGet packages published for MacOS x64-bit  and MacOS ARM64. Would be great to get them published as well. Any plans doing that?

**Comment by amaitland** [comment]
What's the use case?

Cefsharp only runs on windows as it's written in VC++

**Comment by ITDancer13** [comment]
That's true for CefShart. CefGlue on the other hand also provides (basic) implementation for Avalonia which is also running on MacOS. Unfortunately CefGlue has to depend on another package (https://www.nuget.org/packages/cef.redist.osx64) which is not updated frequently. As I want to join as contributor there, I would like to use the same source of redist for all platforms and that would be yours :-)

**Comment by amaitland** [comment]
There are a number of considerations:

**Myget feed space limits**
We are already at the space limit for the free tier

**Maintenance burden**
For me personally the maintenance burden would need to be near zero. Someone would need to contribute all the scripts and package files.

**Build availability**
What happens when CEF builds aren't available for one/both of the Mac architectures. Looks like currently the 64bit beta build isn't available. This happens for different architectures semi regularly.

If there aren't relevant Mac builds available then I'd need an easy option to skip the Mac packages.

> another package (https://www.nuget.org/packages/cef.redist.osx64)

The `cef.redist` package that are included as part of this project will likely be dropped at some point (https://github.com/cefsharp/cef-binary/issues/93). To free up space on the myget feed this would likely need to be resolved.

**Comment by amaitland** [comment]
Closing as this is not something I currently have planned. 

If someone wants to take ownership  of creating/publishing additional packages please continue the discussion at #95
