### ISSUE TITLE
Provide updates packages on nuget

### ISSUE THREAD

**Issue by japj** [cefsharp/cef-binary#51]
The last cef.sdk packages are for chromium v57.
The current stable chromium version is v62.

It would be great if newer versions could be published (separately from if a certain version is already integrated in cefsharp?)

I would have also expected the v59 (3071) to have been published already since the cefsharp master refers to it?

I can help if needed

**Comment by perlun** [comment]
Updating Cef.Redist involves manual work. There's no way to get around that. The builds at http://opensource.spotify.com/cefbuilds/index.html has the new CEF binaries, but _each new Chromium version_ has a different:

- Build number (3162, 3202)
- Version number (61, 62)
- etc

It can't really be automated, unfortunately. 😢 

If you like to submit a PR to this repo which updates to a newer version though, I am all for it. The new versions might _still_ not be usable out-of-the-box with CefSharp (because of breaking changes in the Chromium code base) but then we at least have one of the pieces of the puzzle in place.

**Comment by amaitland** [comment]
@perlun There isn't a whole lot of work required, I automated the process a while back. Just tag a release on GitHub using the full CEF version and appveyor will build and publish Nuget packages to the myget feed. You can then push from myget to  Nuget.org  when and if required. If u need access to the myget feed let me know.

**Comment by perlun** [comment]
@amaitland I obviously haven't paid enough attention lately! 😆 

I logged in at myget and I seem to have the required access. So to reiterate:

- We tag the release here, in this repo
- AppVeyour builds it using `build.ps1`
- The NuGet packages are pushed to myget.
- We can then push them to Nuget.org if we like

Right?

**Comment by amaitland** [comment]
Sounds about right. Test it out, you can delete packages from myget, so there is no harm experimenting

**Comment by perlun** [comment]
We now have CEF62 packages available as of #53, thanks @japj for the friendly reminder. Closing this.
