### ISSUE TITLE
cef.redist.* v3.3497.1841 listed as available upgrade?

### ISSUE THREAD

**Issue by davisford** [cefsharp/cef-binary#72]
![screen shot 2018-11-12 at 12 27 41 pm](https://user-images.githubusercontent.com/186677/48364439-6b911600-e676-11e8-89ac-c6003f0957a2.png)

Why is NuGet showing me that the redist binaries can be upgraded to `3.3497.1841` from `3.3396.1786` for CefSharp `v67.0.0`?

This is on a brand new WinForms project where I just chose to install the latest `CefSharp.WinForms`.  If I try to upgrade them, it errors out and tells me they are incompatible.

Is something wrong with the NuGet packages?  What cef-binary version should I be using for `v67.0.0`?

**Comment by amaitland** [comment]
Issue tracker is for bug reports only, thank you!

If you have a question, ask it on [Gitter](https://gitter.im/cefsharp/CefSharp),  [StackOverflow](http://stackoverflow.com/questions/tagged/cefsharp) or use [ceforum](http://magpcss.org/ceforum/) (for questions specific to `CEF`).

If you are new to `CefSharp` then we suggest you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by amaitland** [comment]
> Is something wrong with the NuGet packages?

No, packages are as expected. If you look at https://www.nuget.org/packages/CefSharp.WinForms/ you'll see there is the `69.0.0-pre01` release, which uses the `3.3497.1841` set of packages.

If you look at https://github.com/cefsharp/CefSharp#release-branches you can see which `CEF` branch (they're actually `Chromium` branch numbers) that corresponds to which version.

**Comment by amaitland** [comment]
See also https://github.com/cefsharp/cef-binary/releases for a list of releases and details of those releases for `cef-binary`

**Comment by perlun** [comment]
A short note to @davisford - the _reason_ why you are seeing the `cef.redist.*` update is that _technically_, the CEF release is _not_ a prerelease - only the _CefSharp_ package (which builds on top of this CEF foundation) is a prerelease.

So, that's why Visual Studio suggests that these packages could be upgraded, but because the prerelease is, well, a prerelease, it will prevent you from getting that update without explicitly opting in to receive prerelease packages (the "include prereleases checkbox" visible in your screenshot.)

(Arguably, it is a bit silly in suggestion an incompatible update matrix like this; feel free to submit a bug report about this to [NuGet](https://github.com/nuget/nuget.client) if you like to discuss it further. Please include your screenshot there as well as a link to this issue.)
